name: "提取数据包翻译"
on: [workflow_dispatch, push]
jobs:
  extract-translate-from-datapack:
    # 使用 ubuntu 最新版本
    runs-on: ubuntu-latest
    steps:
      # 初始化 Python 3.11
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11
      # 安装 jsonfinder
      - name: Install Dependencies
        run: pip install jsonfinder
      # 克隆仓库
      - name: Clone Repository
        run: |
          mkdir hfpro
          cd hfpro
          git clone https://github.com/Heart-Fire-Project/Midsoul.git
          tree -L 6
      # 处理数据包.1
      - name: Pre Progress Datapack
        run: |
          cd ${{ github.workspace }}/hfpro
          cd Midsoul/data
          mkdir lang
          cd lang
          echo '{}' > zh_cn.json
      # 处理数据包.2
      - name: Process Datapack
        run: |
          cd ${{ github.workspace }}/hfpro
          cd Midsoul
          tree -L 6
          wget -O "extract.py" https://raw.githubusercontent.com/Heart-Fire-Project/useful-tools/main/%E6%95%B0%E6%8D%AE%E5%8C%85%E7%BF%BB%E8%AF%91%E6%8F%90%E5%8F%96/%E9%80%82%E7%94%A8%E5%BF%83%E7%81%AB%E5%8E%9F%E5%88%9B%E4%BD%9C%E5%93%81/extract_translate_from_datapack.py
          python3 extract.py
